apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: e5erzmafg-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhopp-rhtap-testing/e5erzmafg-dotnet-basic-gitops